name: Dawson
main: me.ihastechno.dawson.dawson
version: 1.2
description: >
             A simple plugin that provides extra commands, and fun to the game!
commands:
  heal:
    description: Heals you back to full health!
  beam:
    description: Teleport a/the Player/s!